trigger:
  - main

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - script: |
      python --version
      echo "Checked Python version"
    displayName: 'Checking Python Version'

  - script: |
      git --version
      echo "Checked Git version"
    displayName: 'Checking Git Version'

  - script: |
      tree --version
      echo "Checked Tree version"
    displayName: 'Checking Tree Version'

  - script: |
      node -v
      echo "Checked Node version"
    displayName: 'Checking Node Version'