trigger:
  - main

pool:
  vmImage: 'ubuntu-24.04'

steps:
  - script: |
      docker --version
      echo "Checked Docker version"
    displayName: 'Checking Docker Version'

  - script: |
      sudo systemctl status docker
      python helloworld.py
      echo "Checking Docker Engine Status " 
    displayName: 'Checking Docker Engine Status'

  